### ISSUE TITLE
Where did the "dist" folder go?

### ISSUE THREAD

**Issue by cstielper** [marekdedic/imagelightbox#457]
I used to come here and download the "imagelightbox.min.js" and "imagelightbox.min.css" from the "dist" folder to use in my projects. But, that folder no longer exists. How do you use this project now? Thanks.

**Comment by marekdedic** [comment]
Hi,
the build artifacts are no longer included in the repo because this was problematic and it was getting de-synced. I recommend using the latest release from [NPM](https://www.npmjs.com/package/imagelightbox). Alternatively, you can clone the repo and run `npm ci && npm run build` to create the `dist` folder.
