### ISSUE TITLE
HTML5 srcset and sizes

### ISSUE THREAD

**Issue by Buntix** [marekdedic/imagelightbox#49]
'allo!

I've added support for the above (and generic target to image-tag mapping) as on https://github.com/Buntix/imagelightbox and https://github.com/Buntix/imagelightbox#passing-parameters-to-lightbox-images Also added back the link filtering via the 'allowedTypes' config option as it became a lot simpler post the above transform.

All things being equal, it's running at:  http://www.deverecars.com/vehicles.php (using a https://github.com/thephpleague/glide backend).

I've merged in yesterday's upstream changes but not tested. If it seems like something worth adding I can add a pull request :)

**Comment by rejas** [comment]
I gladly take pull requests that add new functionality (which already seems to be needed when I look at your example). Of course, maybe I wouldn't necessarily agree on some technicalities but those could be worked on in a pull request. Could you start with the srcset/size patch first (and later add another PR for the link filtering (since it seems to depend on the former) so we dont mix features before merging them? Cheers, V

**Comment by marekdedic** [comment]
Hi @Buntix ! After all the years, I've finally implemented this one and will release it in the next version :)
